v ; Grassmachine
wwv ; nil
WWwv ; (Grassmachine nil)
wv
wwwwwwwwWWWWWWWWWwwwwwwwwv
wwWWWWwwv
wwv
wWwwWwwwv
wWwwwwWWWWWWWwwwWWwv
wWwwwwwWWWWWWWWwwwWWwv
wWwwwwwwWWWWWWWWWwwwWWwv
wWwwwwwwwWWWWWWWWWWwwwWWwv
wWwwwwwwwwWWWWWWWWWWWwwwWWwv
wWwwwwwwwwWWWWWWWWWWWWwwwWWwv
wWwwwwwwwwwwWWWWWWWWWWWWWwwwWWwv
wWwwwwwwwwwwwWWWWWWWWWWWWWWwwwWWwv
wWwwwwwwwwwwwwWWWWWWWWWWWWWWWwwwWWwv
wWwwwwwwwwwwwwwWWWWWWWWWWWWWWWWwwwWWwv
wWwwwwwwwwwwwwwwWWWWWWWWWWWWWWWWWwwwWWwv
wWwwwwwwwwwwwwwwwWWWWWWWWWWWWWWWWWWwwwWWwv
wWwwwwwwwwwwwwwwwwWWWWWWWWWWWWWWWWWWWwwwWWwv
wWwwwwwwwwwwwwwwwwwWWWWWWWWWWWWWWWWWWWWwwwWWwv
wWwwwwwwwwwwwwwwwwwwWWWWWWWWWWWWWWWWWWWWWwwwWWwv
wWwwwwwwwwwwwwwwwwwwwWWWWWWWWWWWWWWWWWWWWWWwwwWWwv
wWwwwwwwwwwwwwwwwwwwwwWWWWWWWWWWWWWWWWWWWWWWWwwwWWwv
wWwwwwwwwwwwwwwwwwwwwwwWWWWWWWWWWWWWWWWWWWWWWWWwwwWWwv
wWwwwwwwwwwwwwwwwwwwwwwwWWWWWWWWWWWWWWWWWWWWWWWWWwwwWWwv
wWwwwwwwwwwwwwwwwwwwwwwwwWWWWWWWWWWWWWWWWWWWWWWWWWWwwwWWwv
wWwwwwwwwwwwwwwwwwwwwwwwwwWWWWWWWWWWWWWWWWWWWWWWWWWWWwwwWWwv
wWwwwwwwwwwwwwwwwwwwwwwwwwwWWWWWWWWWWWWWWWWWWWWWWWWWWWWwwwWWwv
wWwwwwwwwwwwwwwwwwwwwwwwwwwwWWWWWWWWWWWWWWWWWWWWWWWWWWWWWwwwWWwv
wwwWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWwwv
wWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWwwwwwWWwWwwwwwwv
wWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWwwWWwWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwv
wWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWwwWWwWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwv ; asm: putchar A
w ; main = (Grassmachine nil asm)

;; 34
WWWWWWWWWW
WWWWWWWWWW
WWWWWWWWWW
WWWW
;; 2
ww
